export const categories = [
  { value: "art", label: "Art" },
  { value: "biography", label: "Biography" },
  { value: "business", label: "Business" },
  { value: "children", label: "Children's" },
  { value: "comics", label: "Comics & Graphic Novels" },
  { value: "computers", label: "Computers & Technology" },
  { value: "cooking", label: "Cooking" },
  { value: "economics", label: "Economics" },
  { value: "education", label: "Education" },
  { value: "engineering", label: "Engineering" },
  { value: "fiction", label: "Fiction" },
  { value: "health", label: "Health & Fitness" },
  { value: "history", label: "History" },
  { value: "history/world", label: "World History" },
  { value: "law", label: "Law" },
  { value: "math", label: "Mathematics" },
  { value: "medical", label: "Medical" },
  { value: "music", label: "Music" },
  { value: "mystery", label: "Mystery & Thrillers" },
  { value: "philosophy", label: "Philosophy" },
  { value: "photography", label: "Photography" },
  { value: "poetry", label: "Poetry" },
  { value: "political", label: "Political Science" },
  { value: "religion", label: "Religion" },
  { value: "romance", label: "Romance" },
  { value: "science", label: "Science" },
  { value: "scifi", label: "Science Fiction & Fantasy" },
  { value: "selfhelp", label: "Self Help" },
  { value: "sports", label: "Sports" },
  { value: "tech", label: "Technology" },
  { value: "travel", label: "Travel" },
  { value: "youngadult", label: "Young Adult" },
];
